analyzer:
  plugins:
    - dart_code_metrics

# Lint kuralları devre dışı bırakıldı
# include: package:flutter_lints/flutter.yaml

linter:
  rules: {}

dart_code_metrics:
  rules-exclude:
    - lib/firebase_options.dart
  rules: []