// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzIqW32Zj7Qs9Yuslgbc49gwP8H3AgJI',
    appId: '1:596212807387:web:3b39ac4a6aae56174bbefe',
    messagingSenderId: '596212807387',
    projectId: 'fal-app-f63dc',
    authDomain: 'fal-app-f63dc.firebaseapp.com',
    storageBucket: 'fal-app-f63dc.firebasestorage.app',
    measurementId: 'G-0XRJ9LYZNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6OjPwCLBibJV5WPofMO-S2WZOctOacJQ',
    appId: '1:596212807387:android:c6dbe803bebbe7934bbefe',
    messagingSenderId: '596212807387',
    projectId: 'fal-app-f63dc',
    storageBucket: 'fal-app-f63dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOOmwg6SH9WjWho4ZKAkx6oqBTtWOWxeQ',
    appId: '1:596212807387:ios:46c7a912b0c4a2774bbefe',
    messagingSenderId: '596212807387',
    projectId: 'fal-app-f63dc',
    storageBucket: 'fal-app-f63dc.firebasestorage.app',
    iosBundleId: 'com.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOOmwg6SH9WjWho4ZKAkx6oqBTtWOWxeQ',
    appId: '1:596212807387:ios:46c7a912b0c4a2774bbefe',
    messagingSenderId: '596212807387',
    projectId: 'fal-app-f63dc',
    storageBucket: 'fal-app-f63dc.firebasestorage.app',
    iosBundleId: 'com.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHzIqW32Zj7Qs9Yuslgbc49gwP8H3AgJI',
    appId: '1:596212807387:web:3b39ac4a6aae56174bbefe',
    messagingSenderId: '596212807387',
    projectId: 'fal-app-f63dc',
    authDomain: 'fal-app-f63dc.firebaseapp.com',
    storageBucket: 'fal-app-f63dc.firebasestorage.app',
    measurementId: 'G-0XRJ9LYZNG',
  );

}